language: python
matrix:
  include:
   - python: "3.5"
   - python: "3.6"
   - python: "nightly"
  allow_failures:
   - python: "nightly"

install:
 - "make build"

script:
 - "make test"
 - "make typecheck"
