language: python
matrix:
  include:
   - python: "3.5"
   - python: "3.6"
   - python: "nightly"
  allow_failures:
   - python: "nightly"

install:
 - "pip install -r dev-requirements.txt"
 - "make build"

script:
 - "make test"
